# Generated by Django 2.1.4 on 2018-12-22 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Member', max_length=30)),
                ('description', models.TextField(default="Describe this role's functionality.")),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_roles', to='account.Committee')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('committee', 'name')},
        ),
    ]
